version: '3.8'

services:
  database:
    image: postgres
    container_name: mypostgres
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./volumes:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - app-network

  bot:
    build: .
    command: python3 bot.py
    working_dir: "/usr/src/app"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
